# Generated by Django 5.1.6 on 2025-02-12 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_manage.users')),
            ],
        ),
    ]
